<? 

	$mandatasistem="Anda dapat mengubah nilai berbagai data sistem/kantor melalui form di bawah ini. Apabila pengubahan selesai, klik 'Simpan'";
	$mantambahdana="Untuk menambah data sumber dana, ketikkan ID (otomatis) dan keterangan sumber dana.  Kemudian klik Tambah.";


	$mantambahlibur = "Untuk menambah data hari libur, pilih tanggal dan isi keterangan hari libur.  Setelah itu klik 'Tambah'";
	$manupdatelibur = "Untuk mengupdate data hari libur yang telah ada, pilih tanggal dan isi keterangan hari libur.  Setelah itu klik 'Update'";
	$manlihatlibur = "Untuk mengupdate data hari libur yang  ada pada daftar, klik 'update' pada kolom 'Update'.  Untuk menghapus data hari libur, pilih  klik kotak pada kolom 'Hapus' dan klik tombol 'Hapus'";
	$manlihatawallibur = "Untuk melihat data hari libur, pilih tahun, kemudian klik OK";

?>