<? 

$mantambahpegawai="Untuk menambah data pegawai, silakan mengisi isian di bawah ini dan klik 'Tambah'";
$manupdatepegawai="Untuk mengupdate data pegawai, silakan mengubah isian di bawah ini dan klik 'Update'.  Untuk isian password, password yang lama tidak akan diubah apabila password tidak diisi.";
$manupdatepegawai2="Untuk mengupdate data pegawai, silakan mengisi ID pegawai yang hendak diupdate dan klik 'Update'";
$manhapuspegawai="Untuk menghapus data pegawai, silakan mengisi ID pegawai yang hendak dihapus dan klik 'Hapus'";
$manlihatdaftarpegawai="Untuk melihat daftar pegawai, pilih filter yang dinginkan dan klik 'OK'.";

$mantambahjabatan="Untuk menambah data jabatan, ketikkan ID (otomatis) dan keterangan jabatan. Kemudian klik Tambah.";
$mantambahlokasi="Untuk menambah data lokasi, ketikkan ID (otomatis) dan keterangan lokasi. Kemudian klik Tambah.";
$mantambahbidang="Untuk menambah data bidang, ketikkan ID (otomatis) dan keterangan lokasi. Kemudian klik Tambah.";
$mantambahstatuspegawai="Untuk menambah data status, ketikkan ID (otomatis) dan keterangan status. Kemudian klik Tambah.";

?>